#!/bin/bash
#
# Set up users for papasan server
#

function die() {
    echo "$*" 1>&2
    exit 1
}

[ $(id --user) -ne 0 ] && die "Must be root to create users"

function group_exists() {
    getent group $* > /dev/null 2>&1
}

function user_exists() {
    getent passwd $* > /dev/null 2>&1
}

group_exists papasan || groupadd papasan || :
user_exists papasan || useradd papasan -g papasan --create-home --shell /bin/false || :

user_exists administrator || {
    useradd administrator -g papasan -p '$1$FadedFad$R7Jyfdzk5j2RBUA5y3z.z1' --create-home || :
}

: vim:autoindent
: vim:expandtab
