#!/bin/bash
#
# Extract the windows password from the EC2 instance data
#

function die {
    echo "$*" 1>&2
    exit 1
}

function warn {
    echo "$*" 1>&2
}

hostname=${1}
[ -z "$hostname" ] && die "usage: $0 hostname"
json=/var/cache/papasan/aws/$hostname.json

[ -f $json ] || die "no json config for $hostname"

id=$( jq --raw-output '.["Instances"][0]["InstanceId"]' $json )

case "$id" in
"") die "invalid instance" ;;
i-*) ;;
esac

# find out when it is live
# extract the password
# find the public IP
raw=$( aws --region us-west-2  ec2  get-password-data --instance $id | jq --raw-output '.["PasswordData"]' | tr -d ' \015' )
[ "$raw" = "null" ] && die "Password not ready yet"
# warn "Password <$raw>"
echo "$raw" | base64 -d | openssl rsautl -decrypt -inkey .ssh/DRaaS-serveraws.pem

# add a newline to the output
echo ""

# vim:autoindent expandtab
